### ISSUE TITLE
ImportError: cannot import name 'container_abcs' from 'torch._six'

### ISSUE THREAD

**Issue by fedorov** [Mayo-Radiology-Informatics-Lab/IDC_GoogleCloud_Notebook#1]
Do I need a specific, older version of one of the packages?

![image](https://user-images.githubusercontent.com/313942/122615559-b9ecc980-d056-11eb-8d35-30fe62911eca.png)

**Comment by kevin-vmi** [comment]
I think we don't need a specific version of smp if we work on google cloud VM. 

Also, we can comment this line "import segmentation_models_pytorch as smp", since I rewrote the segmentation model and smp was not used any more.
