### ISSUE TITLE
User should be authenticated

### ISSUE THREAD

**Issue by fedorov** [Mayo-Radiology-Informatics-Lab/IDC_GoogleCloud_Notebook#2]
Currently, the notebook will fail trying to run the `bigquery` cell, since the user has not been authenticated. The code below should be added before trying to run an operation that requires user to be authenticated:

```python
from google.colab import auth
auth.authenticate_user()
```

**Comment by kevin-vmi** [comment]
Hi, Fedorov, I just noticed your messages. Sorry for my late replies!

I have run the notebook again and also checked with my colleagues. I think these two lines are required if we work on collab. However, my notebook was prepared on GCP VM. I suggest you also try it on google cloud and see if it is working.

FYI, you can find the env settings in the front page README.md.

**Comment by kevin-vmi** [comment]
> Currently, the notebook will fail trying to run the `bigquery` cell, since the user has not been authenticated. The code below should be added before trying to run an operation that requires user to be authenticated:
> 
> ```python
> from google.colab import auth
> auth.authenticate_user()
> ``


I thought more on your suggestions. I will work on my notebook to see if it can be turned compatible to both GCP and  Colab.  Will keep you posted. Thanks!

**Comment by kevin-vmi** [comment]
New notebook version uploaded. Now it should work for both GCP and Colab environments. 

Thanks for your comments!
