### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fedorov** [Mayo-Radiology-Informatics-Lab/IDC_GoogleCloud_Notebook#3]
Line 3 in the cell below has a problem.

![image](https://user-images.githubusercontent.com/313942/122616633-b9edc900-d058-11eb-9fea-5a297a0a6a0b.png)

**Comment by fedorov** [comment]
Also, it looks like you need to specify the full path to `.pylidcrc` - `/root/.pylidcrc`.

**Comment by kevin-vmi** [comment]
Hi, Fedorov, I guess it is similar to the other issues that the GCP VM env is required, as the goal of this notebook is to examine the feasibility of working on GCP with IDC. 

In my running, the path to _.pylidcrc_ is _/home/jupyter/.pylidcrc_. Thanks!

**Comment by kevin-vmi** [comment]
> Line 3 in the cell below has a problem.
> 
> ![image](https://user-images.githubusercontent.com/313942/122616633-b9edc900-d058-11eb-9fea-5a297a0a6a0b.png)

Resolved. Full path to _.pylidcrc_ is added in the new version for Colab users. @fedorov
